### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tb-sa-plugins#1] opened 2016-06-25 03:56 UTC
Don't forget, you may be able to remove jQuery, since it is already running in the environment the plugin will exist in. Slip that baby down! :-P

**Comment by jorgefelico** [comment] 2016-06-25 05:09
I'll have to look into it some more. I've been reading and it says that the extension runs in a "sandboxed" mode which doesn't let us access any of the in-page scripts. HOWEVER, I was able to overcome this by injecting JS into the page when adding the Emmet plugin feature to the editor. Just takes a bit more tinkering...

**Comment by michaelspellacy** [comment] 2016-06-25 06:24
Ah, I see. Okay then. :-)

**Comment by Brockenstein** [comment] 2018-08-16 18:34
Closing issues because I have confirmed that the chrome script can not utilize the jquery running on the page.

**Closed by Brockenstein** 2018-08-16 18:34 UTC
